import json

with open('kaggle_notebook/notebook.ipynb', 'r', encoding='utf-8') as f:
    nb = json.load(f)

cell1 = {
    'cell_type': 'code', 'execution_count': None, 'metadata': {}, 'outputs': [],
    'source': [
        '# CELL 1 - Install PyTorch 2.5.1 (T4/sm_75 compatible) + dependencies\n',
        '# Kaggle Latest Container has PyTorch compiled only for sm_80+ (no T4 support)\n',
        '# Force reinstall PyTorch 2.5.1 which includes sm_75 (T4) CUDA kernels\n',
        'import subprocess, sys\n',
        'print("Installing PyTorch 2.5.1 with CUDA 12.1 (T4/sm_75 compatible)...")\n',
        'subprocess.run([sys.executable, "-m", "pip", "install", "-q", "-U",\n',
        '    "torch==2.5.1", "torchvision==0.20.1",\n',
        '    "--index-url", "https://download.pytorch.org/whl/cu121"], check=True)\n',
        'print("Installing diffusers and other deps...")\n',
        'subprocess.run([sys.executable, "-m", "pip", "install", "-q",\n',
        '    "diffusers==0.32.2", "transformers==4.46.3", "accelerate", "sentencepiece"], check=True)\n',
        'subprocess.run([sys.executable, "-m", "pip", "install", "-q",\n',
        '    "fastapi", "uvicorn", "pyngrok", "imageio[ffmpeg]"], check=True)\n',
        'subprocess.run([sys.executable, "-m", "pip", "install", "-q",\n',
        '    "opencv-python", "pillow", "numpy", "huggingface_hub>=0.23.0"], check=True)\n',
        'import torch\n',
        'print("PyTorch version:", torch.__version__)\n',
        'print("CUDA available:", torch.cuda.is_available())\n',
        'if torch.cuda.is_available():\n',
        '    print("GPU:", torch.cuda.get_device_name(0))\n',
        '    print("Compute capability:", torch.cuda.get_device_capability(0))\n',
        'import diffusers\n',
        'print("Diffusers version:", diffusers.__version__)\n',
        'print("LTXPipeline available:", hasattr(diffusers, "LTXPipeline"))\n',
        'print("All dependencies installed!")'
    ]
}

cell2 = {
    'cell_type': 'code', 'execution_count': None, 'metadata': {}, 'outputs': [],
    'source': [
        '# CELL 2 - Setup Kaggle Credentials\n',
        'import os\n',
        'try:\n',
        '    from kaggle_secrets import UserSecretsClient\n',
        '    user_secrets = UserSecretsClient()\n',
        '    kaggle_user = user_secrets.get_secret("KAGGLE_USERNAME")\n',
        'except:\n',
        '    kaggle_user = os.environ.get("KAGGLE_USERNAME", "__KAGGLE_USERNAME_PLACEHOLDER__")\n'
    ]
}

cell3 = {
    'cell_type': 'code', 'execution_count': None, 'metadata': {}, 'outputs': [],
    'source': [
        '# CELL 3 - Load LTX model and start FastAPI server\n',
        'import sys, os\n',
        'PKGS = "/kaggle/working/pkgs"\n',
        'if PKGS not in sys.path:\n',
        '    sys.path.insert(0, PKGS)\n',
        'import threading, uvicorn, torch, time, base64, traceback, requests\n',
        'from fastapi import FastAPI\n',
        'from fastapi.responses import JSONResponse\n',
        'from pydantic import BaseModel\n',
        '# Import LTXPipeline (this is the correct class name in diffusers >= 0.33.1)\n',
        'try:\n',
        '    from diffusers import LTXPipeline\n',
        'except ImportError:\n',
        '    from diffusers.pipelines.ltx import LTXPipeline\n',
        'from diffusers.utils import export_to_video\n',
        'from pyngrok import ngrok\n',
        'print("Diffusers version in Cell 3:", __import__("diffusers").__version__)\n',
        'print("LTXPipeline loaded:", LTXPipeline)\n',
        '\n',
        'try:\n',
        '    from kaggle_secrets import UserSecretsClient\n',
        '    user_secrets = UserSecretsClient()\n',
        '    kaggle_user = user_secrets.get_secret("KAGGLE_USERNAME")\n',
        'except:\n',
        '    kaggle_user = os.environ.get("KAGGLE_USERNAME", "__KAGGLE_USERNAME_PLACEHOLDER__")\n',
        '\n',
        'backend_url = "https://alonejutt2288--cartoon-backend-fastapi-modal-app.modal.run/session/register-url"\n',
        '\n',
        'try:\n',
        '    # T4 sm_75: disable torch.compile & force sync errors for debugging\n',
        '    os.environ["TORCH_COMPILE_DISABLE"] = "1"\n',
        '    os.environ["CUDA_LAUNCH_BLOCKING"] = "1"\n',
        '    os.environ["PYTORCH_CUDA_ALLOC_CONF"] = "expandable_segments:True"\n',
        '    print("Loading LTX-Video pipeline with CPU offload (T5 on CPU, transformer on GPU)...")\n',
        '    # float16: T4 sm_75 supports it natively\n',
        '    # enable_model_cpu_offload: T5-XXL (~10 GiB) stays on CPU RAM,\n',
        '    # only the LTX transformer (~5 GiB) uses GPU VRAM\n',
        '    pipe = LTXPipeline.from_pretrained("Lightricks/LTX-Video", torch_dtype=torch.float16)\n',
        '    pipe.enable_model_cpu_offload()   # T5 on CPU, transformer on GPU\n',
        '    # Disable flash & mem-efficient SDP — only math kernel works on sm_75\n',
        '    torch.backends.cuda.enable_flash_sdp(False)\n',
        '    torch.backends.cuda.enable_mem_efficient_sdp(False)\n',
        '    torch.backends.cuda.enable_math_sdp(True)\n',
        '    pipe.enable_attention_slicing(1)\n',
        '    print(f"GPU: {torch.cuda.get_device_name(0)}, VRAM: {torch.cuda.get_device_properties(0).total_memory // 1024**3}GB")\n',
        '    print("LTX-Video ready! (float16 + CPU offload: T5 on RAM, transformer on GPU)")\n',
        '\n',
        '    app = FastAPI()\n',
        '    last_activity = time.time()\n',
        '    IDLE_TIMEOUT = 8 * 60 * 60\n',
        '\n',
        '    class GenerateRequest(BaseModel):\n',
        '        prompt: str\n',
        '        scene_id: str\n',
        '        account_id: str\n',
        '\n',
        '    @app.post("/generate")\n',
        '    def generate_video(request: GenerateRequest):\n',
        '        global last_activity\n',
        '        last_activity = time.time()\n',
        '        print(f"Generating: {request.prompt}")\n',
        '        try:\n',
        '            print(f"[GEN] Starting: {request.prompt[:80]}")\n',
        '            torch.cuda.empty_cache()\n',
        '            # Force math-only SDPA (no flash/mem-efficient — sm_75 compat)\n',
        '            with torch.inference_mode(), torch.backends.cuda.sdp_kernel(enable_flash=False, enable_math=True, enable_mem_efficient=False):\n',
        '                result = pipe(\n',
        '                    prompt=request.prompt,\n',
        '                    negative_prompt="low quality, worst quality, deformed, distorted, disfigured, motion smear, motion artifacts, fused fingers, bad anatomy, weird hand, ugly",\n',
        '                    width=512, height=288,\n',
        '                    num_frames=25,\n',
        '                    num_inference_steps=30,\n                    max_sequence_length=256,\n',
        '                    guidance_scale=3.5,\n',
        '                    generator=torch.Generator("cuda").manual_seed(42),\n',
        '                )\n',
        '            frames = result.frames[0]\n',
        '            output_file = f"/kaggle/working/{request.scene_id}.mp4"\n',
        '            export_to_video(frames, output_file, fps=8)\n',
        '            with open(output_file, "rb") as f:\n',
        '                video_b64 = base64.b64encode(f.read()).decode()\n',
        '            print(f"[GEN] Done: {output_file}")\n',
        '            last_activity = time.time()\n',
        '            return {"status": "success", "video_path": output_file, "video_b64": video_b64}\n',
        '        except Exception as e:\n',
        '            tb = traceback.format_exc()\n',
        '            print("[GEN ERROR]", tb)\n',
        '            return JSONResponse(status_code=500, content={"status": "error", "message": str(e), "traceback": tb})\n',
        '\n',
        '    @app.get("/health")\n',
        '    def health():\n',
        '        return {"status": "alive", "model": "LTX-Video"}\n',
        '\n',
        '    def idle_checker():\n',
        '        global last_activity\n',
        '        while True:\n',
        '            time.sleep(30)\n',
        '            if time.time() - last_activity > IDLE_TIMEOUT:\n',
        '                print("Idle 10 min. Shutting down...")\n',
        '                os._exit(0)\n',
        '\n',
        '    threading.Thread(target=idle_checker, daemon=True).start()\n',
        '    threading.Thread(target=lambda: uvicorn.run(app, host="0.0.0.0", port=8000), daemon=True).start()\n',
        '    print("FastAPI server ready on port 8000!")\n',
        '\n',
        '    # Start ngrok tunnel & Register with backend\n',
        '    try:\n',
        '        user_secrets = UserSecretsClient()\n',
        '        ngrok_token = user_secrets.get_secret("NGROK_TOKEN")\n',
        '    except:\n',
        '        ngrok_token = os.environ.get("NGROK_TOKEN", "__NGROK_TOKEN_PLACEHOLDER__")\n',
        '\n',
        '    if ngrok_token:\n',
        '        ngrok.set_auth_token(ngrok_token)\n',
        '\n',
        '    public_url = ngrok.connect(8000).public_url\n',
        '    print(f"Ngrok URL: {public_url}")\n',
        '\n',
        '    resp = requests.post(backend_url, json={"account_username": kaggle_user, "url": public_url})\n',
        '    print("Registered:", resp.json())\n',
        '\n',
        '    print("System fully ready! Waiting for generation requests...")\n',
        '    while True:\n',
        '        time.sleep(60)\n',
        '\n',
        'except Exception as e:\n',
        '    error_msg = traceback.format_exc()\n',
        '    print("CRASH ERROR:", error_msg)\n',
        '    requests.post(backend_url, json={"account_username": kaggle_user, "url": f"ERROR: {str(e)} - {error_msg[-200:]}"})\n',
        '    raise e\n'
    ]
}

nb['cells'] = [cell1, cell2, cell3]

with open('kaggle_notebook/notebook.ipynb', 'w', encoding='utf-8') as f:
    json.dump(nb, f, indent=1)

print('notebook.ipynb updated to LTX-Video successfully!')
